# Generated by Django 2.2.8 on 2019-12-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
                ('gpioPort', models.IntegerField(unique=True, verbose_name='Porta')),
                ('state', models.BooleanField(choices=[(True, 'Ligado'), (False, 'Desligado'), (None, 'Desconhecido')], default=None, null=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
                ('gpioPort', models.IntegerField(unique=True, verbose_name='Porta')),
                ('value', models.FloatField(verbose_name='Valor atual')),
                ('max_value', models.FloatField(verbose_name='Valor de saturacao')),
                ('min_value', models.FloatField(verbose_name='Valor de referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Rotina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('sensorControl', models.BooleanField(default=False, verbose_name='Controlado por sensor?')),
                ('mon', models.BooleanField(default=False, verbose_name='Segunda-Feira')),
                ('tue', models.BooleanField(default=False, verbose_name='Terca-Feira')),
                ('wed', models.BooleanField(default=False, verbose_name='Quarta-Feira')),
                ('thu', models.BooleanField(default=False, verbose_name='Quinta-Feira')),
                ('fri', models.BooleanField(default=False, verbose_name='Sexta-Feira')),
                ('sat', models.BooleanField(default=False, verbose_name='Sabado')),
                ('sun', models.BooleanField(default=False, verbose_name='Domingo')),
                ('startHour', models.TimeField(null=True, verbose_name='Inicio')),
                ('endHour', models.TimeField(null=True, verbose_name='Fim')),
                ('threshold', models.FloatField(default=0, null=True, verbose_name='Valor de ativacao')),
                ('comparison', models.CharField(choices=[('>', 'Maior que'), ('<', 'Menor que')], max_length=1, verbose_name='Modo de comparacao')),
                ('activation', models.BooleanField(choices=[(True, 'Ligar'), (False, 'Desligar')], default=True, verbose_name='Acao de ativacao')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoHomeInterface.Saida', verbose_name='Saida controlada')),
                ('sensor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoHomeInterface.Sensor', verbose_name='Sensor de controle')),
            ],
        ),
    ]
