# Generated by Django 2.2.8 on 2019-12-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoHomeInterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotina',
            name='activation',
            field=models.BooleanField(blank=True, choices=[(True, 'Ligar'), (False, 'Desligar')], default=True, verbose_name='Acao de ativacao do sensor'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='comparison',
            field=models.CharField(blank=True, choices=[('>', 'Maior que'), ('<', 'Menor que')], max_length=1, verbose_name='Modo de comparacao do sensor com valor de ativacao'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='endHour',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='sensor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoHomeInterface.Sensor', verbose_name='Sensor de controle'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='startHour',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='rotina',
            name='threshold',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Valor de ativacao'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='state',
            field=models.BooleanField(blank=True, choices=[(True, 'Ligado'), (False, 'Desligado'), (None, 'Desconhecido')], default=None, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_value',
            field=models.FloatField(blank=True, verbose_name='Valor de saturacao'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='min_value',
            field=models.FloatField(blank=True, verbose_name='Valor de referencia'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='value',
            field=models.FloatField(blank=True, verbose_name='Valor atual'),
        ),
    ]
